<?php

$data = array("Lession 1",
["able",
"elastic",
"low",
"secret",
"acid",
"electric",
"male",
"separate",
"angry",
"equal"],
["http://audio.oxforddictionaries.com/en/mp3/able_gb_1.mp3",
"http://audio.oxforddictionaries.com/en/mp3/elastic_gb_1.mp3",
"http://audio.oxforddictionaries.com/en/mp3/low_gb_1.mp3",
"http://audio.oxforddictionaries.com/en/mp3/secret_gb_2.mp3",
"http://audio.oxforddictionaries.com/en/mp3/acid_gb_1.mp3",
"http://audio.oxforddictionaries.com/en/mp3/electric_gb_1.mp3",
"http://audio.oxforddictionaries.com/en/mp3/male_gb_1.mp3",
"http://audio.oxforddictionaries.com/en/mp3/separate_gb_1.mp3",
"http://audio.oxforddictionaries.com/en/mp3/angry_gb_1.mp3",
"http://audio.oxforddictionaries.com/en/mp3/equal_gb_1.mp3"],
["ˈeɪb(ə)l",
"ɪˈlastɪk",
"ləʊ",
"ˈsiːkrɪt",
"ˈasɪd",
"ɪˈlɛktrɪk",
"ˈmɑːleɪ",
"ˈsɛpəreɪt",
"ˈaŋɡri",
"ˈiːkw(ə)l"],

["có năng lực, có tài.",
"co giãn ((nghĩa đen) & (nghĩa bóng)), đàn hồi; mềm dẻo.",
"tiếng rống (trâu bò).",
"kín đáo, thầm kín, bí mật; riêng tư.",
"(hoá học) Axit.",
"(thuộc) điện, có điện, phát điện.",
"chỉ giống đực.",
"riêng rẽ, rời, không dính với nhau.",
"Giận, tức giận, cáu.",
"Bằng, ngang bằng."],
["an able co-op manager.",
"the labour supply is very elastic.",
"to put a car in low.",
"the secret of health is temperature.",
"acid radical.",
"an electric torch.",
"male friend.",
"the two questions are essentially separate.",
"the secrets of nature",
"a equals b"]);	

echo json_encode($data);

?>